// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18hnRJ_wtRrTVcj0kYb1Y7Qbwp5FGd5k',
    appId: '1:875406220149:web:4e9e0831630466b651d13c',
    messagingSenderId: '875406220149',
    projectId: 'gourmet-app-31aab',
    authDomain: 'gourmet-app-31aab.firebaseapp.com',
    storageBucket: 'gourmet-app-31aab.firebasestorage.app',
    measurementId: 'G-F32CTT30X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkfS0anRj5JTJYXwAxH13EHglE5j4w1So',
    appId: '1:875406220149:android:19fef96ea04a6e8e51d13c',
    messagingSenderId: '875406220149',
    projectId: 'gourmet-app-31aab',
    storageBucket: 'gourmet-app-31aab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgiliEdZ1cndnsqs4VfY17gH_4sKOg1TI',
    appId: '1:875406220149:ios:bbc4ec505832f72b51d13c',
    messagingSenderId: '875406220149',
    projectId: 'gourmet-app-31aab',
    storageBucket: 'gourmet-app-31aab.firebasestorage.app',
    iosBundleId: 'com.example.gourmetApp',
  );

}